image: node:10.10.0

cache:
  paths:
    - node_modules/

before_script:
  - npm install

test_async:
  script:
    - npm run test
  only:
    - dev

pages:
  stage: deploy
  script:
    - npm run docs:build
  artifacts:
    paths:
      - public
  only:
    - master
